projects:
  api:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  adminApi:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4001
  prisma:
    schemaPath: src/generated/prisma-client/prisma.ts
    extensions:
      prisma: prisma/prisma.yml
